title: ML-Notes
description: Handbook of technical notes for machine learning.
theme: just-the-docs

url: https://prithvi-ramrucha.github.io/mlnotes

# Configure sidebar,
just_the_docs:
  collapse_navigation: true
  custom_head: _includes/head_custom.html

plugins:
  - jekyll-include-cache
