title: ML-Notes
description: Handbook of technical notes for machine learning.
theme: just-the-docs

url: https://prithvi-ramrucha.github.io/mlnotes

# Configure sidebar,
just_the_docs:
  show_sidebar: true
  collapsible_sidebar: true

#aux_links: 
  #Template Repository: https://github.com/prithvi-ramrucha/mlnotes
