title: ML-Notes
description: Handbook of technical notes for machine learning.
theme: just-the-docs

url: https://prithvi-ramrucha.github.io/mlnotes

#aux_links: 
  #Template Repository: https://github.com/prithvi-ramrucha/mlnotes
